
spring:
  # Config
  datasource:
    url: jdbc:h2:mem:test_db
    username: sa
    password:
  # Web Client
  h2:
    console:
      enabled: true
      path: /h2-console
  # View sql
  jpa:
    show-sql: true
  properties:
    hibernate:
      format_sql: true